# Generated by Django 6.1.1 on 2026-09-14 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0002_rename_product_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ky',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_name_ky',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(blank=True, choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='avito_app.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='avito_app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
